app/models/employee.py
from app.extensions import db

class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(50), unique = True)
    phone_number = db.Column(db.String(11), unique = True)
    position = db.Column(db.String(40))
    shift = db.Column(db.DateTime)
    birth_day = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def __repr__(self):
        return f'<Employee {self.name}>'

app/models/events.py
from app.extensions import db

class Events(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(50))
    description = db.Column(db.Text)
    start_date = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def __repr__(self):
        return f'<Event {self.title}>'

app/models/item.py
from app.extensions import db

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    brand = db.Column(db.String(80))
    quantity = db.Column(db.Double)
    price = db.Column(db.Double)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def __repr__(self):
        return f'<Item {self.name}>'
    
    

app/models/users.py
from app.extensions import db

class Users(db.Model):
    
    __tablename__ = 'users'
    
    id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(50))
    email=db.Column(db.String(50), unique=True)
    password=db.Column(db.String(50))
    userIcon = db.Column(db.String(50))
    
    def __repr__(self):
        return f'<Users {self.name}>'

app/__init__.py
from flask import Flask
from app.extensions import db
from config import Config


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    db.init_app(app)
    
    
    from app.home import bp as main_bp
    app.register_blueprint(main_bp)
    
    from app.login import bp as login_bp
    app.register_blueprint(login_bp)

    return app

app/home/__init__.py
from flask import Blueprint

bp = Blueprint('home', __name__)

from app.home import routes

app/home/routes.py
from flask import render_template
from app.home import bp

@bp.route('/')
def index():
    return render_template('index.html')

app/login/__init__.py
from flask import Blueprint

bp = Blueprint('login', __name__)

from app.login import routes

app/login/routes.py
from flask import render_template
from app.login import bp

@bp.route('/login')
def login():
    return render_template('login.html')

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/2e1a73f3fe.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="static/styles.css">
    <title>gerenciamento de recursos</title>
  </head>
  <body>
    <div class="main">
      <div class="side-bar">
        <a class="icon-frame" href="{{ url_for('login.login') }}">
          <i class="fa-solid fa-user"></i>
          <span class="icon-frame-text">login</span>
        </a>
        <div class="navigation">
          <span>Estoque</span>
          <span>Funcionários</span>
          <span>Calendário</span>
        </div>
        <div class="extras">
          <span><i class="fa-solid fa-headset"></i> Suporte</span>
          <span><i class="fa-solid fa-gear"></i> Opções</span>
        </div>
      </div>
    </div>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <script src="https://kit.fontawesome.com/2e1a73f3fe.js" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="static/styles.css">
        <title>login</title>
    </head>
    <body>
        <div class="main">
            <div class="login">
                <form action="/login" method="POST">
                    <div class="form-box">
                      <label for="username">Username:</label>
                      <input type="text" id="username" name="username" required placeholder="Your email address" autocomplete="off">
                    </div>
                    <div class="form-box">
                      <label for="password">Password:</label>
                      <input type="password" id="password" name="password" required placeholder="Your password">
                    </div>
                    <div class="form-box">
                        <button type="submit">Sign in</button>
                    </div>
                    <a href="#signup">Don't have an account? Sign up</a>
                  </form>
            </div>
        </div>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/2e1a73f3fe.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="static/styles.css">
    <title>gerenciamento de recursos</title>
  </head>
  <body>
    <div class="main">
      <div class="side-bar">
        <a class="icon-frame" href="{{ url_for('login') }}">
          <i class="fa-solid fa-user"></i>
          <span class="icon-frame-text">login</span>
        </a>
        <div class="navigation">
          <span>Estoque</span>
          <span>Funcionários</span>
          <span>Calendário</span>
        </div>
        <div class="extras">
          <span><i class="fa-solid fa-headset"></i> Suporte</span>
          <span><i class="fa-solid fa-gear"></i> Opções</span>
        </div>
      </div>
    </div>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
  </body>
</html>